language: elixir
elixir:
#  - 1.0.0
  - 1.0.1
  - 1.0.2
  - 1.0.3
  - 1.0.4
otp_release:
  - 17.0
  - 17.1
  - 17.3
  - 17.4
  - 17.5
  - 18.0
sudo: false
script: mix test
after_script:
  - mix hex.config username $HEX_USERNAME
  - mix hex.config key $HEX_KEY
  - mix hex.docs
  - deps.get --only docs
  - MIX_ENV=docs mix inch.report
