language: erlang
otp_release:
  - 17.3
before_install:
  - wget http://s3.hex.pm/builds/elixir/v1.0.2.zip
  - unzip -d elixir v1.0.2.zip
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - mix deps.get
script: mix test
after_script:
  - mix hex.config username $HEX_USERNAME
  - mix hex.config key $HEX_KEY
  - mix hex.docs
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
